version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: monitoring_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    networks:
      - inventory_network

  grafana:
    image: grafana/grafana
    container_name: monitoring_grafana
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - inventory_network

  node-exporter:
    image: prom/node-exporter
    container_name: monitoring_node_exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - inventory_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: monitoring_cadvisor
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inventory_network

  mongodb-exporter:
    image: percona/mongodb_exporter
    container_name: monitoring_mongodb_exporter
    environment:
      - MONGODB_URI=mongodb://inventory_mongo:27017
    ports:
      - "9216:9216"
    restart: always
    networks:
      - inventory_network

volumes:
  grafana_data:

networks:
  inventory_network:
    external: true