version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: inventory_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./data-redis:/data
    networks:
      - inventory_network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-123456}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-123456}

networks:
  inventory_network:
    external: true

volumes:
  redis_data:
    driver: local
