version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: inventory_elasticsearch
    restart: unless-stopped
    user: '1000:1000'
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'true'
      ELASTIC_USERNAME: ${ELASTICSEARCH_USERNAME:-elastic}
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD:-aHR0cHM6Ly9raWJhbmEuaW52ZW50b3J5LXN5c3RlbS5jbG91ZC8=}
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
    volumes:
      - ./data-elasticsearch:/usr/share/elasticsearch/data
    networks:
      - inventory_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s -u ${ELASTICSEARCH_USERNAME:-elastic}:${ELASTICSEARCH_PASSWORD:-aHR0cHM6Ly9raWJhbmEuaW52ZW50b3J5LXN5c3RlbS5jbG91ZC8=} http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  inventory_network:
    external: true

volumes:
  es_data:
    driver: local
